GluGluHto2Mu:
  crossSection: GluGluHto2Mu
  generator: powheg

TTH_Hto2Mu:
  crossSection: TTH_Hto2Mu
  generator: powheg

VBFHto2Mu:
  crossSection: VBFHto2Mu
  generator: powheg =

custom_CI:
  crossSection: VBFHto2Mu
  generator: powheg
  fs_nanoAOD: T3_CH_CERNBOX:/store/user/vdamante/
  dirName: "nano24"

Muon1_Run2024C:
  fs_nanoAOD: T3_CH_CERNBOX:/store/user/vdamante/
  dirName: "nano24_data"

WminusH_Hto2Mu_WtoAll:
  crossSection: WminusH_Hto2Mu_WtoAll
  generator: powheg
WplusH_Hto2Mu_WtoAll:
  crossSection: WplusH_Hto2Mu_WtoAll
  generator: powheg
ZH_Hto2Mu_ZtoAll:
  crossSection: ZH_Hto2Mu_ZtoAll
  generator: powheg
