#### DY samples ####
# DYto2L_2Jets_EWK_MLL_50:
#   crossSection: DYto2L_2Jets_EWK_MLL_50_LO
#   crossSectionStitch: DYto2Mu_MLL_105to160_amcatnloFXFX
#   generator: amcatnlo
#   nanoAOD:
#     v15:

DYto2Mu_MLL_105to160_amcatnloFXFX:
  crossSection: DYto2Mu_MLL_105to160_amcatnloFXFX
  crossSectionStitch: DYto2Mu_MLL_105to160_amcatnloFXFX
  generator: amcatnlo
  miniAOD: /DYto2Mu-2Jets_Bin-MLL-105to160_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24MiniAODv6-150X_mcRun3_2024_realistic_v2-v2/MINIAODSIM
  nanoAOD:
    v15: /DYto2Mu-2Jets_Bin-MLL-105to160_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAOD-140X_mcRun3_2024_realistic_v26-v2/NANOAODSIM
    v15: /DYto2Mu-2Jets_Bin-MLL-105to160_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM

##### EWK Samples #####

EWK_2L2J_madgraph_herwig:
  crossSection: EWK_2L2J_MLL50_MJJ120
  generator: madgraph
  nanoAOD:
    v15: /EWK-2L2J_Bin-MLL-50-MJJ-120_TuneCH3_13p6TeV_madgraph-herwig7/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM

EWK_2Mu2J_MLL_105to160_herwig:
  crossSection: EWK_2Mu2J_MLL105to160_MJJ120
  generator: madgraph
  nanoAOD:
    v15: /EWK-2Mu2J_Bin-MLL-105to160_TuneCH3_13p6TeV_madgraph-herwig7/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM

EWK_2Mu2J_MLL_105to160_pythia:
  crossSection: EWK_2Mu2J_MLL105to160_MJJ120
  generator: madgraph
  nanoAOD:
    v15: /EWK-2Mu2J_Bin-M2Mu-105to160-M2J-120_TuneCP5_13p6TeV_madgraph-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM


#### TTLNu-EWK Samples ####
TTLNu-EWK_amcatnlo:
  crossSection: TTLNu_EWK
  generator: amcatnlo
  nanoAOD:
    v15: /TTLNu-EWK_TuneCP5_13p6TeV_amcatnlo-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM

### Other EWK samples ###
# WZto3LNu-2Jets_EWK_QCD:
#   crossSection: WZto3LNu_2Jets_EWK_QCD
#   generator: madgraph
#   nanoAOD:
#     v15: N/A

WmWmJJ_EWK:
  crossSection: WmWmJJ_EWK
  generator: powheg
  nanoAOD:
    v15: /WmWmJJ-EWK_TuneCP5_13p6TeV-powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM


### Higgs samples ###
GluGluHto2Mu:
  crossSection: GluGluHto2Mu
  generator: powheg
  nanoAOD:
    v15: /GluGluH-Hto2Mu_Par-M-125_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
GluGluHto2Mu_MiNNLO: # currently missing
  crossSection: GluGluHto2Mu
  generator: powheg
  miniAOD:
  nanoAOD:
    v15:
VBFHto2Mu_M125_powheg:
  crossSection: VBFHto2Mu
  generator: powheg
  nanoAOD:
    v15: /VBFH-Hto2Mu_Par-M-125_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
VBFHto2Mu_M125_tuneCP5Up_amcatnlo:
  crossSection: VBFHto2Mu
  generator: amcanlo
  nanoAOD:
    v15: /VBF-Hto2Mu_Par-M-125_TuneCP5Up_13p6TeV_amcatnlo-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
VBFHto2Mu_M125_tuneCP5Down_amcatnlo:
  crossSection: VBFHto2Mu
  generator: amcanlo
  nanoAOD:
    v15: /VBF-Hto2Mu_Par-M-125_TuneCP5Down_13p6TeV_amcatnlo-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
VBFHto2Mu_M120_amcatnlo:
  crossSection: VBFHto2Mu
  generator: amcanlo
  nanoAOD:
    v15: /VBF-Hto2Mu_Par-M-120_TuneCP5_13p6TeV_amcatnlo-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
VBFHto2Mu_M125_amcatnlo:
  crossSection: VBFHto2Mu
  generator: amcanlo
  nanoAOD:
    v15: /VBF-Hto2Mu_Par-M-125_TuneCP5_13p6TeV_amcatnlo-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
VBFHto2Mu_M130_amcatnlo:
  crossSection: VBFHto2Mu
  generator: amcanlo
  nanoAOD:
    v15: /VBF-Hto2Mu_Par-M-130_TuneCP5_13p6TeV_amcatnlo-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM

ZH_Hto2Mu:
  crossSection: ZH_Hto2Mu_ZtoAll
  generator: powheg
  nanoAOD:
    v15: /ZH-Hto2Mu_Par-M-125_TuneCP5_13p6TeV_powhegMINLO-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v3/NANOAODSIM
WplusH_Hto2Mu:
  crossSection: WplusH_Hto2Mu_WtoAll
  generator: powheg
  nanoAOD:
    v15: /WplusH-Hto2Mu_Par-M-125_TuneCP5_13p6TeV_powhegMINLO-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v3/NANOAODSIM
WminusH_Hto2Mu:
  crossSection: WminusH_Hto2Mu_WtoAll
  generator: powheg
  nanoAOD:
    v15: /WminusH-Hto2Mu_Par-M-125_TuneCP5_13p6TeV_powhegMINLO-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v3/NANOAODSIM
TTH_Hto2Mu:
  crossSection: TTH_Hto2Mu
  generator: powheg
  nanoAOD:
    v15: /TTH-Hto2Mu_Par-M-125_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
