triggerFile: config/Run3_2024/triggers.yaml
bTagAlgo: UParTAK4
corrections:
  btag:
    stages: [ AnaTuple ]
    modes:
      AnaTuple: none
    tagger: UParTAK4
    jetCollection: Jet
    wantShape: False
  mu:
    stage: HistTuple
    columns:
      pfRelIso04_all: pfRelIso04_all
      tightId: tightId
      tkRelIso: tkRelIso
      highPtId: highPtId
      mediumId: mediumId
      looseId: looseId
      p4: p4_bsConstrainedPt # p4_pt_nano
  trigger:
    stage: HistTuple
    mode: SF
    extraFormat:
      pt: "bsConstrainedPt"
  muScaRe:
    stage: AnaTuple # later it will become anaTuple.
    # stage: HistTuple # later it will become anaTuple.
    mu_pt_for_ScaReApplication: "bsConstrainedPt"
  MC_Lumi_pu: { stage: AnaTuple }
  pu: { stages: [ AnaCache, AnaTuple ] }
  JEC: { stage: AnaTuple }
  JER:
    stage: AnaTuple
    apply_jet_horns_fix: true
