GLOBAL:
  sampleSelection:
    - drop ^.*
    - keep ^.*Hto2Mu.*
    - keep ^EWK_.*
    - keep ^DYto2L_M_10to50_amcatnloFXFX.*
    - keep ^DYto2L_M_50_amcatnloFXFX.*
    - drop ^DYto2L_M_50_PTLL_.*
    - drop ^DYto2Mu_MLL_*
    - keep DYto2Mu_MLL_50to120_powheg
    - keep DYto2Mu_MLL_105to160_amcatnloFXFX
    - keep DYto2Mu_MLL_120to200_powheg
    - keep DYto2Mu_MLL_200to400_powheg
    - keep ^DYToMuMu-M50_13p6TeV_MiNNLO_pythia8.*
    - keep ^GluGlutoContinto.*
    - drop ^GluGlutoContinto2Zto2E2Nu  # missing XS
    - drop ^GluGlutoContinto2Zto2Mu2Nu  # missing XS
    - keep ^ggZH*
    - keep ^Tbar*
    - keep ^TBbar*
    - keep ^TW*
    - keep ^TT.*
    - keep ^TTto.*
    - keep ^TTH.*
    - keep ^WminusH*
    - keep ^WplusH*
    - keep ^WtoLNu_.*amcatnloFXFX.*
    - keep ^WW.*
    - keep ^WZ.*
    - keep ^ZZ.*
    - keep ^ZH*
    - keep ^VBFH.*
    - keep ^GluGluH.*
    - drop Zto2(Nu|Q)_.*
    - drop ^.*Run2023*
    - keep ^Muon_.*
    - keep ^Muon0_.*
    - keep ^Muon1_.*
    # - keep ^MuonEG_.*
    - keep ^SingleMuon_.*
    - drop ^.*ext*
    - keep ^LLJJ.*
    - drop EWK_2L2J_madgraph_herwig  # tmp - missing XS
    - drop LLJJ_SM_M-50_MJJ120_13p6TeV_herwig7  # missing gen info
    - drop LLJJ_SM_M-50_MJJ120_13p6TeV_herwig7_ext1  # missing gen info
    - drop LLJJ_SM_M-50_MJJ120_13p6TeV_herwig7_ext2  # missing gen info

  use_stitching: False
  triggerFile: config/Run3_2022EE/triggers.yaml

GluGluHto2Mu:
  sampleType: ggH
  crossSection: GluGluHto2Mu
  generator: powheg

TTH_Hto2Mu:
  sampleType: ttH
  crossSection: TTH_Hto2Mu
  generator: powheg

VBFHto2Mu:
  sampleType: VBFH
  crossSection: VBFHto2Mu
  generator: powheg

WminusH_Hto2Mu_WtoAll:
  sampleType: VH
  crossSection: WminusH_Hto2Mu_WtoAll
  generator: powheg
WplusH_Hto2Mu_WtoAll:
  sampleType: VH
  crossSection: WplusH_Hto2Mu_WtoAll
  generator: powheg
ZH_Hto2Mu_ZtoAll:
  sampleType: VH
  crossSection: ZH_Hto2Mu_ZtoAll
  generator: powheg


GluGluHto2Mu_M_120_TuneCp5:
  sampleType: ggH
  crossSection: <da vedere>
  generator: amcatnlo
  fs_nanoAOD: T2_US_MIT:/store/group/phys_higgs/cmshmm/amarini/{}/Run3Summer2022-NANOAODSIMv12/241010_133402/




DYto2Mu_MLL_105to160_amcatnloFXFX:
  crossSection: DYto2Mu_MLL_105to160_amcatnloFXFX
  crossSectionStitch: DYto2Mu_MLL_105to160_amcatnloFXFX
  generator: amcatnlo
  miniAOD: /DYto2Mu_MLL_105to160_amcatnloFXFX/Run3Summer22MiniAODv4-130X_mcRun3_2022_realistic_v5-v1/MINIAODSIM
  sampleType: DY