meta_data:
  nBatches: 1000
  global_config: /afs/cern.ch/user/a/ayeagle/H_mumu/config/global.yaml
  general_config: /afs/cern.ch/user/a/ayeagle/H_mumu/Studies/DNN/ds_setup/general.yaml
  temp_folder: /eos/user/a/ayeagle/H_mumu/temp_files/
  output_folder: /eos/user/a/ayeagle/H_mumu/root_files/v2vbfselnew/Run3_2022/
  input_folder: /eos/user/v/vdamante/H_mumu/anaTuples/v2_VBFSel_Studies_new/Run3_2022

dataset_list:
 - WWto2L2Nu_powheg
 - WWto4Q_powheg
 - WWtoLNu2Q_powheg
 - WZto2L2Q_powheg
 - WZto3LNu_powheg
 - WZtoLNu2Q_powheg

 - ZZto2L2Nu_powheg
 - ZZto2L2Q_powheg
 - ZZto2Nu2Q_powheg
 - ZZto4L_powheg

 - TTto2L2Nu
 - TTto4Q
 - TTtoLNu2Q

 - DYto2L_M_10to50_amcatnloFXFX
 - DYto2L_M_50_amcatnloFXFX
 - DYto2Mu_MLL_105to160_amcatnloFXFX
 - DYto2Mu_MLL_50to120_powheg
 - DYto2Mu_MLL_120to200_powheg
 - DYto2Mu_MLL_200to400_powheg

 - GluGluHto2Mu
 - VBFHto2Mu

 - LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole
 - LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_ext1
 - LLJJ_SM_M-50_MJJ120_13p6TeV_dipole
 - LLJJ_SM_M-50_MJJ120_13p6TeV_dipole_ext1
