############## DY ##############
DY:
  name: "DY 012 jets"
  cross_section_correction: 12/ 11  # NLO -> NNLO
  color: "kAzure+7"
  color_mplhep: lightskyblue
  datasets:
    - DYto2E_M_50_0J_amcatnloFXFX
    - DYto2Mu_M_50_0J_amcatnloFXFX
    # - DYto2Tau_M_50_0J_Filtered_amcatnloFXFX
    - DYto2Tau_M_50_0J_amcatnloFXFX
    - DYto2E_M_50_1J_amcatnloFXFX
    - DYto2Mu_M_50_1J_amcatnloFXFX
    # - DYto2Tau_M_50_1J_Filtered_amcatnloFXFX
    - DYto2Tau_M_50_1J_amcatnloFXFX
    - DYto2E_M_50_2J_amcatnloFXFX
    - DYto2Mu_M_50_2J_amcatnloFXFX
    # - DYto2Tau_M_50_2J_Filtered_amcatnloFXFX
    - DYto2Tau_M_50_2J_amcatnloFXFX


DY_mll_105To160:
  name: "DY mll 105 to 160 "
  cross_section_correction: 12/ 11  # NLO -> NNLO
  color: "kAzure+7"
  color_mplhep: lightskyblue
  datasets:
    - DYto2Mu_MLL_105to160_amcatnloFXFX
############## TT ##############
TT:
  name: "t $\\bar{t}$"
  color: "kGreen-3"  # eliminates need for plot.yaml
  color_mplhep: darkblue  # turquoise
  datasets:
    - TTto2L2Nu
    - TTtoLNu2Q
    - TTto4Q

TT_Inclusive:
  name: "t#bar{t} Inclusive"
  color: "kGreen-3"
  color_mplhep: darkgreen  # turquoise
  datasets:
    - TT


############## WJetsToLNu ##############
W:
  name: "W"
  color: "kGreen"  # eliminates need for plot.yaml
  color_mplhep: yellow
  datasets:
    - WtoLNu_amcatnloFXFX

W_NJets:
  name: "W $\\rightarrow \\ell \\nu$+ jets"
  color: "kGreen"  # eliminates need for plot.yaml
  color_mplhep: yellow
  datasets:
    - WtoLNu_0J_amcatnloFXFX
    - WtoLNu_1J_amcatnloFXFX
    - WtoLNu_2J_amcatnloFXFX

############## EWK ##############
EWK_LLJJ:
  name: "EWK"
  color: kMagenta+3
  color_mplhep: darkmagenta
  datasets: [ ]

EWK:
  name: "EWK"
  color: kMagenta+3
  color_mplhep: darkmagenta
  datasets:
    - EWK_2L2J_madgraph_herwig

EWK_LLJJ_herwig:
  name: "EWK"
  color: kMagenta+3
  color_mplhep: darkmagenta
  datasets: [ ]

EWK_LLJJ_M105_160:
  name: "EWK"
  color: kMagenta+3
  color_mplhep: darkmagenta
  datasets: [ ]

EWK_LLJJ_M105_160_VBFFilter:
  name: "EWK"
  color: kMagenta+3
  color_mplhep: darkmagenta
  datasets: [ ]

############## Other single H  ##############
H_mainBckg:
  name: "Single H"
  color: kPink
  color_mplhep: aqua
  datasets:
    - GluGluHto2Tau_UncorrelatedDecay_Filtered
    - GluGluHto2Tau_UncorrelatedDecay_UnFiltered
    - GluGluHto2B_M125
    - VBFHto2B_M125
    - VBFHto2Tau_UncorrelatedDecay_UnFiltered
    - VBFHto2Tau_UncorrelatedDecay_Filtered
    - GluGluHto2Wto2L2Nu_M125

############## VV ##############
VV_Inclusive:
  name: "VV Inclusive"
  color: kPink+2
  color_mplhep: tomato
  datasets:
    - WW
    - WZ
    - ZZ

VV:
  name: "VV"
  color: kPink+2
  color_mplhep: tomato
  datasets:
    - WWto2L2Nu_powheg
    - WWto4Q_powheg
    - WWtoLNu2Q_powheg
    - WZto3LNu_powheg
    - WZto2L2Q_powheg
    - WZtoLNu2Q_powheg
    - ZZto2L2Nu_powheg
    - ZZto2L2Q_powheg
    - ZZto2Nu2Q_powheg
    - ZZto4L_powheg

############## VH non-inclusive ##############
VH_inclusive:
  name: "VH"
  color: kPink+2
  color_mplhep: slateblue
  datasets:
    - ZH_Hto2B_Zto2L
    - ZH_Hto2B_Zto2Q
    - ggZH_Hto2B_Zto2L
    - ggZH_Hto2B_Zto2Q
    - WminusH_Hto2B_Wto2Q
    - WminusH_Hto2B_WtoLNu
    - WplusH_Hto2B_Wto2Q
    - WplusH_Hto2B_WtoLNu

############## VVV inclusive ##############
VVV:
  name: "VVV"
  color: kOrange-4
  color_mplhep: plum
  datasets:
    - WWW_4F
    - WWZ_4F
    - WZZ
    - ZZZ

############## ST ##############
ST:
  name: "ST"
  color: kCyan-1
  color_mplhep: cyan
  datasets:
    - TbarBtoLminusNuB_s_channel_4FS
    - TBbartoLplusNuBbar_s_channel_4FS
    - TbarBQ_t_channel_4FS
    - TBbarQ_t_channel_4FS


############## TW ##############
TW:
  name: "TW"
  color: kCyan-1
  color_mplhep: green
  datasets:
    - TWminusto2L2Nu
    - TWminusto4Q
    - TWminustoLNu2Q
    - TbarWplusto2L2Nu
    - TbarWplusto4Q
    - TbarWplustoLNu2Q

############## TTX ##############
TTX:
  name: "TT+X"
  color: kBlue-10
  color_mplhep: pink
  datasets:
    - TTWH
    - TTWW
    - TTZH
    - TTZZ
    # - TTZ_Zto2Q

TTX_2023:
  name: "TT+X"
  color: kBlue-10
  color_mplhep: pink
  datasets:
    - TTWH
    - TTWW
    - TTZH
    - TTZZ

############## VBF signal ##############

VBFHto2Mu:
  name: "VBFHto2Mu"
  color: "kPink"
  color_mplhep: fuchsia
  datasets:
    - VBFHto2Mu

VBFHto2Mu_Herwig:
  name: "VBFHto2Mu_Herwig"
  color: "kPink"
  color_mplhep: fuchsia
  datasets: [ ]
#     - VBFHto2Mu_M-125_13p6TeV_powheg-herwig7
#     # - VBFHto2Mu_M-125_13p6TeV_powheg-herwig7_ext1
#     # - VBFHto2Mu_M-125_13p6TeV_powheg-herwig7_ext2

############## ggH signal ##############

GluGluHto2Mu:
  name: "GluGluHto2Mu"
  color: "kCyan"
  color_mplhep: cyan
  datasets:
    - GluGluHto2Mu

############## VH signal ##############

VHto2Mu:
  name: "VHto2Mu"
  color: "kPink"
  color_mplhep: red
  datasets:
    - WminusH_Hto2Mu_WtoAll
    - WplusH_Hto2Mu_WtoAll
    - ZH_Hto2Mu_ZtoAll

############## TTH signal ##############

TTHto2Mu:
  name: "TTHto2Mu"
  color: "kPink"
  color_mplhep: red
  datasets:
    - TTHto2Mu

TTH_inclusive:
  name: "ttH"
  color: "kpink"
  color_mplhep: red
  datasets:
    - TTHtoNon2B_M125
    - TTHto2B_M125

Data_Full:
  name: "Data"
  datasets: [ ]
Data_EGamma0:
  name: "Data EGamma0"
  datasets:
    - EGamma0_Run2023D_v1
    - EGamma0_Run2023D_v2

Data_EGamma1:
  name: "Data EGamma1"
  datasets:
    - EGamma1_Run2023D_v1
    - EGamma1_Run2023D_v2

Data_Muon:
  name: "Data Muon 0 "
  datasets:
    - Muon0_Run2023D_v1
    - Muon0_Run2023D_v2
    - Muon1_Run2023D_v1
    - Muon1_Run2023D_v2

Data_MuonEG:
  name: "Data MuonEG"
  datasets:
    - MuonEG_Run2023D_v1
    - MuonEG_Run2023D_v2
