

########## mu1 BEGIN ##########
mu1_pt:
  x_bins: "200|0:1000"
  x_rebin:
    other: [0, 5,10,15, 20,25, 30,35, 40,45, 50,55, 60,65, 70,75, 80,85, 90,95,100, 105,110,115, 120,125, 130, 135, 150, 165, 180, 200]
  x_title: p_{T}(mu_{1}) (GeV)
  y_title: "#frac{Events}{bin width} #left(#frac{1}{GeV}#right) "
  #y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  # use_log_y: True
  # max_y_sf: 20.2
  divide_by_bin_width: True
  #divide_by_bin_width: False

mu1_eta:
  x_bins: "120|-3.:3."
  x_rebin: [-2.5, -2.3, -2.1, -1.9, -1.7, -1.5, -1.3, -1.1, -0.9, -0.7, -0.5, -0.3, -0.1, 0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.1, 2.3, 2.5]
  x_title: \eta(mu_{1})
  y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  divide_by_bin_width: False

mu1_phi:
  x_bins: "100|-3.2:3.2"
  x_rebin: [-3.2, -2.88, -2.56, -2.24, -1.92, -1.6, -1.28, -0.96, -0.64, -0.32, -0.0, 0.32, 0.64, 0.96, 1.28, 1.6, 1.92, 2.24, 2.56, 2.88, 3.2]
  x_title: \phi(mu_{1})
  y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  divide_by_bin_width: False


########## mu1 END ##########


########## mu2 BEGIN ##########
mu2_pt:
  x_bins: "200|0:1000"
  x_rebin:
    other: [0, 5,10,15, 20,25, 30,35, 40,45, 50,55, 60,65, 70,75, 80,85, 90,95,100, 105,110,115, 120,125, 130, 135, 150, 165, 180, 200]
  x_title: p_{T}(mu_{2}) (GeV)
  y_title: "#frac{Events}{bin width} #left(#frac{1}{GeV}#right) "
  #y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  # use_log_y: True
  # max_y_sf: 20.2
  divide_by_bin_width: True
  #divide_by_bin_width: False


mu2_eta:
  x_bins: "120|-3.:3."
  x_rebin: [-2.5, -2.3, -2.1, -1.9, -1.7, -1.5, -1.3, -1.1, -0.9, -0.7, -0.5, -0.3, -0.1, 0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.1, 2.3, 2.5]
  x_title: \eta(mu_{2})
  y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  divide_by_bin_width: False

mu2_phi:
  x_bins: "100|-3.2:3.2"
  x_rebin: [-3.2, -2.88, -2.56, -2.24, -1.92, -1.6, -1.28, -0.96, -0.64, -0.32, -0.0, 0.32, 0.64, 0.96, 1.28, 1.6, 1.92, 2.24, 2.56, 2.88, 3.2]
  x_title: \phi(mu_{2})
  y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  divide_by_bin_width: False


########## mu2 END ##########


########## muMu BEGIN ##########

pt_mumu:
  x_bins: "200|0:1000"
  x_rebin:
    other: [0, 5,10,15, 20,25, 30,35, 40,45, 50,55, 60,65, 70,75, 80,85, 90,95,100, 105,110,115, 120,125, 130, 135, 150, 165, 180, 200]
  x_title: p_{T}(\mu\mu) (GeV)
  y_title: "#frac{Events}{bin width} #left(#frac{1}{GeV}#right) "
  y_title: Events
  use_log_x: False
  use_log_y: False
  max_y_sf: 1.8
  # use_log_y: True
  # max_y_sf: 20.2
  divide_by_bin_width: True

m_mumu:
  x_bins: "1000|0:1000"
  x_rebin: [69,70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111]
  x_title: M(\mu\mu) (GeV)
  # y_title: Events
  y_title: "#frac{Events}{bin width} #left(#frac{1}{GeV}#right) "
  use_log_x: False
  use_log_y: False
  max_y_sf: 1.8
  # use_log_y: True
  # max_y_sf: 20.2
  # divide_by_bin_width: False
  divide_by_bin_width: True

dR_mumu:
  x_bins: "50|0:5"
  x_rebin: [0.5, 0.6, 0.7, 0.8,0.9, 1.0,1.1, 1.2,1.3, 1.4,1.5, 1.6,1.7, 1.8, 1.9,2.0, 2.1,2.2,2.3, 2.4,2.5, 2.6,2.7, 2.8,2.9, 3.0]
  x_title: \Delta R(\mu\mu)
  y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  divide_by_bin_width: False

eta_mumu:
  x_bins: "200|-5.:5."
  # x_rebin: [-2.5, -2.3, -2.1, -1.9, -1.7, -1.5, -1.3, -1.1, -0.9, -0.7, -0.5, -0.3, -0.1, 0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.1, 2.3, 2.5]
  x_title: \eta(mu_{1}, \mu_{2})
  y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  divide_by_bin_width: False

y_mumu:
  x_bins: "150|-3.:3."
  x_rebin: [-2.5, -2.3, -2.1, -1.9, -1.7, -1.5, -1.3, -1.1, -0.9, -0.7, -0.5, -0.3, -0.1, 0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.1, 2.3, 2.5]
  x_title: y(mu_{1}, \mu_{2})
  y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  divide_by_bin_width: False

phi_mumu:
  x_bins: "260|-6.5:6.5"
  x_rebin: [-2.5, -2.3, -2.1, -1.9, -1.7, -1.5, -1.3, -1.1, -0.9, -0.7, -0.5, -0.3, -0.1, 0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.1, 2.3, 2.5]
  x_title: \phi(mu_{1}, \mu_{2})
  y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  divide_by_bin_width: False

phi_CS:
  x_bins: "100|-3.2:3.2"
  x_rebin: [-3.2, -2.88, -2.56, -2.24, -1.92, -1.6, -1.28, -0.96, -0.64, -0.32, -0.0, 0.32, 0.64, 0.96, 1.28, 1.6, 1.92, 2.24, 2.56, 2.88, 3.2]
  x_title: \phi_{CS}
  y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  divide_by_bin_width: False

cosTheta_CS:
  x_bins: "202|-1.01:1.01"
  x_rebin: [-1., -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3,-0.2, -0.1, 0., 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.,]
  x_title: cos(\theta_{CS})
  y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  divide_by_bin_width: False


########## muMu END ##########

########## j1 BEGIN ##########
j1_pt:
  x_bins: "200|0:1000"
  x_rebin:

    other: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90,100, 120,140, 160, 180, 200, 220, 240, 260, 280, 300, 350, 400, 500]
  x_title: p_{T}(j_{1}) (GeV)
  y_title: "#frac{Events}{bin width} #left(#frac{1}{GeV}#right) "
  #y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  # use_log_y: True
  # max_y_sf: 20.2
  divide_by_bin_width: True
  #divide_by_bin_width: False


j1_eta:
  x_bins: "192|-4.8:4.8"
  x_rebin: [-4.8, -4.6, -4.4, -4.2, -4., -3.8, -3.6, -3.4, -3.2, -3., -2.8, -2.6, -2.4, -2.2, -2., -1.8, -1.6, -1.4, -1.2, -1., -0.8, -0.6, -0.4, -0.2, 0., 0.2, 0.4, 0.6, 0.8, 1., 1.2, 1.4, 1.6, 1.8, 2., 2.2, 2.4, 2.6, 2.8, 3., 3.2, 3.4, 3.6, 3.8, 4., 4.2, 4.4, 4.6, 4.8]
  x_title: \eta(j_{1})
  y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  divide_by_bin_width: False

j1_phi:
  x_bins: "128|-3.2:3.2"
  x_rebin: [-3.2, -2.88, -2.56, -2.24, -1.92, -1.6, -1.28, -0.96, -0.64, -0.32, -0.0, 0.32, 0.64, 0.96, 1.28, 1.6, 1.92, 2.24, 2.56, 2.88, 3.2]
  x_title: \phi(j_{1})
  y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  divide_by_bin_width: False


########## j1 END ##########


########## j2 BEGIN ##########
j2_pt:
  x_bins: "200|0:1000"
  x_rebin:
    other:  [0, 10, 20, 30, 40, 50, 60, 70, 80, 90,100, 120,140, 160, 180, 200, 220, 240, 260, 280, 300, 350, 400, 500]
  x_title: p_{T}(j_{2}) (GeV)
  y_title: "#frac{Events}{bin width} #left(#frac{1}{GeV}#right) "
  #y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  # use_log_y: True
  # max_y_sf: 20.2
  divide_by_bin_width: True
  #divide_by_bin_width: False


j2_eta:
  x_bins: "192|-4.8:4.8"
  x_rebin: [-4.8, -4.6, -4.4, -4.2, -4., -3.8, -3.6, -3.4, -3.2, -3., -2.8, -2.6, -2.4, -2.2, -2., -1.8, -1.6, -1.4, -1.2, -1., -0.8, -0.6, -0.4, -0.2, 0., 0.2, 0.4, 0.6, 0.8, 1., 1.2, 1.4, 1.6, 1.8, 2., 2.2, 2.4, 2.6, 2.8, 3., 3.2, 3.4, 3.6, 3.8, 4., 4.2, 4.4, 4.6, 4.8]
  x_title: \eta(j_{2})
  y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  divide_by_bin_width: False

j2_phi:
  x_bins: "128|-3.2:3.2"
  x_rebin: [-3.2, -2.88, -2.56, -2.24, -1.92, -1.6, -1.28, -0.96, -0.64, -0.32, -0.0, 0.32, 0.64, 0.96, 1.28, 1.6, 1.92, 2.24, 2.56, 2.88, 3.2]
  x_title: \phi(j_{2})
  y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  divide_by_bin_width: False


########## j2 END ##########

########## j system BEGIN ##########

Zepperfield_Var:
  x_bins: "100|0:2"
  x_rebin:
    other:  [0., 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0]
  x_title: M(j_{2},j_{2}) (GeV)
  # y_title: Events
  y_title: "#frac{Events}{bin width} #left(#frac{1}{GeV}#right) "
  use_log_x: False
  use_log_y: False
  max_y_sf: 1.8
  # use_log_y: True
  # max_y_sf: 20.2
  # divide_by_bin_width: False
  divide_by_bin_width: True


pt_centrality:
  x_bins: "100|0:10"
  x_rebin:
    other: [0., 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 10.0]
  x_title: M(j_{2},j_{2}) (GeV)
  # y_title: Events
  y_title: "#frac{Events}{bin width} #left(#frac{1}{GeV}#right) "
  use_log_x: False
  use_log_y: False
  max_y_sf: 1.8
  # use_log_y: True
  # max_y_sf: 20.2
  # divide_by_bin_width: False
  divide_by_bin_width: True

R_pt:
  x_bins: "100|0:10"
  x_rebin:
    other: [0., 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1]
  x_title: M(j_{2},j_{2}) (GeV)
  # y_title: Events
  y_title: "#frac{Events}{bin width} #left(#frac{1}{GeV}#right) "
  use_log_x: False
  use_log_y: False
  max_y_sf: 1.8
  # use_log_y: True
  # max_y_sf: 20.2
  # divide_by_bin_width: False
  divide_by_bin_width: True

m_jj:
  x_bins: "1000|0:1000"
  x_rebin:
    other: [ 400, 420, 440, 460, 480, 500, 520, 540, 560, 580, 600, 620, 640, 660, 680, 700, 800, 900, 1000] # ,105, 110,115,120,125, 130,135,140,145, 150]
    # baseline_Zmumu: [  70, 71, 72, 73, 74,75,76,77,78,79, 80,81,82,83,84,85,86,87,88,89, 90,91,92,93,94,95,96,97,98,99, 100] # ,105, 110,115,120,125, 130,135,140,145, 150]
    # VBF_Zmumu: [  70, 71, 72, 73, 74,75,76,77,78,79, 80,81,82,83,84,85,86,87,88,89, 90,91,92,93,94,95,96,97,98,99, 100] # ,105, 110,115,120,125, 130,135,140,145, 150]
    # ggH_Zmumu: [  70, 71, 72, 73, 74,75,76,77,78,79, 80,81,82,83,84,85,86,87,88,89, 90,91,92,93,94,95,96,97,98,99, 100] # ,105, 110,115,120,125, 130,135,140,145, 150]
    # VBF_Zmumu_JetVeto: [  70, 71, 72, 73, 74,75,76,77,78,79, 80,81,82,83,84,85,86,87,88,89, 90,91,92,93,94,95,96,97,98,99, 100] # ,105, 110,115,120,125, 130,135,140,145, 150]
    # ggH_Zmumu_JetVeto: [  70, 71, 72, 73, 74,75,76,77,78,79, 80,81,82,83,84,85,86,87,88,89, 90,91,92,93,94,95,96,97,98,99, 100] # ,105, 110,115,120,125, 130,135,140,145, 150]
  x_title: M(j_{2},j_{2}) (GeV)
  # y_title: Events
  y_title: "#frac{Events}{bin width} #left(#frac{1}{GeV}#right) "
  use_log_x: False
  use_log_y: False
  max_y_sf: 1.8
  # use_log_y: True
  # max_y_sf: 20.2
  # divide_by_bin_width: False
  divide_by_bin_width: True

delta_eta_jj:
  x_bins: "400|-10.:10."
  x_rebin: [-8.5, -8.,-7.5,-7.0,-6.5,-6.0,-5.5,-5.0,-4.5,-4.0,-3.5,-3.0, -2.5, 2.5,3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.,8.5]
  x_title: \Delta\eta(jj)
  y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  divide_by_bin_width: False

minDeltaEta:
  x_bins: "400|-10.:10."
  x_rebin: [2.5,3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.,8.5]
  x_title: min(\Delta\eta(\mu\mu, j))
  y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  divide_by_bin_width: False

minDeltaEtaSigned:
  x_bins: "400|-10.:10."
  x_rebin: [-8.5, -8.,-7.5,-7.0,-6.5,-6.0,-5.5,-5.0,-4.5,-4.0,-3.5,-3.0, -2.5, 2.5,3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.,8.5]
  x_title: min(\Delta\eta(\mu\mu, j))
  y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  divide_by_bin_width: False


minDeltaPhi:
  x_bins: "100|-3.2:3.2"
  x_rebin: [-3.2, -2.88, -2.56, -2.24, -1.92, -1.6, -1.28, -0.96, -0.64, -0.32, -0.0, 0.32, 0.64, 0.96, 1.28, 1.6, 1.92, 2.24, 2.56, 2.88, 3.2]
  x_title: min(\Delta\phi(\mu\mu, j))
  y_title: Events
  use_log_y: False
  max_y_sf: 1.8
  divide_by_bin_width: False