lumi_text:
  text: "7.9804 fb^{-1} (13.6 TeV)"
  pos_ref: inner_right_top
  pos: [ 0., -0.035 ]
  text_size: 0.035
  font: 42
  align: right_bottom

channel_text:
  'muMu': '#mu#mu'

customregion_text:
  'Z_sideband': 'Z SideBand'
  'Signal_Fit': 'Signal Fit'
  'H_sideband': 'H SideBand'
  'Signal_ext': 'Signal extension'
  'mass_inclusive': 'Inclusive'
