# https://twiki.cern.ch/twiki/bin/viewauth/CMS/TauTrigger#Updates_for_2022_data_taking

singleMu:
  channels:
    - muMu
  path:
    - HLT_IsoMu24
  legs:
    - offline_obj:
        cut: "{obj}_legType == Leg::mu && {obj}_pt > 26"  # {obj}_pt > 26 && abs({obj}_eta) < 2.4
      online_obj:
        cut: TrigObj_id == 13 && (TrigObj_filterBits&8)!=0
      doMatching: True
      jsonTRGcorrection_key: { "2022_Summer22": "NUM_IsoMu24_DEN_CutBasedIdMedium_and_PFIsoMedium",
                               "2022_Summer22EE": "NUM_IsoMu24_DEN_CutBasedIdMedium_and_PFIsoMedium",
                               "2023_Summer23": "NUM_IsoMu24_DEN_CutBasedIdMedium_and_PFIsoMedium",
                               "2023_Summer23BPix": "NUM_IsoMu24_DEN_CutBasedIdMedium_and_PFIsoMedium"
      }
      jsonTRGcorrection_elepath: "placeholder"
