fs_default:
  - /builds/cms-flaf/flaf_integration/output/H_mumu

analysis_config_area: config
compute_unc_variations: true
compute_unc_histograms: true
store_noncentral: true

variables:
  - DNN_NNOutput
  - mu1_pt
