meta_data:
  global_config: /afs/cern.ch/work/v/vdamante/H_mumu/config/global.yaml
  output_folder: /eos/user/v/vdamante/H_mumu/test/
  input_folder: /eos/user/e/eusebi/Hmumu/anaTuples/v4_20Nov_NewJetIDs_LooseMuons/
  selection_cut: Signal_ext

sample_list:
  #- DY
  # - EWK
  - GluGluHto2Mu
  # - VBFHto2Mu
  # - TT
  # - VV
  # - ST
  # - VVV
  # - TW
  # - TTX
  # - data

