BaseModel:
  name: "Base Model"
  backgrounds:
    - TT
    - DY
    - DYToMuMu_MiNNLO
    - DYToMuMu_amcatnloFXFX
    # - W
    - W_NJets
    # - EWK
    - EWK_LLJJ
    # - EWK_LLJJ_herwig
    - H_mainBckg
    - ST
    - TW
    - TTH_inclusive
    - TTX
    - VH_inclusive
    - VV
    - VVV
  signals:
    - VBFHto2Mu
    - VBFHto2Mu_Herwig
    - GluGluHto2Mu
  data:
    - Data_Muon
