BaseModel:
  name: "Base Model"
  backgrounds:
    - DY
    - TT
    - VV
    - EWK
    - W_NJets
    - ST
    - TW
    - VVV
    - TTX
    - H_mainBckg
    - TTH_inclusive
    - VH_inclusive
  signals:
    - VBFHto2Mu
    # - VBFHto2Mu_Herwig
    - GluGluHto2Mu
  # data:
    # - Data_Muon

TestModel:
  name: "Test model for CI"
  signals:
    - custom_CI

TestModel_withData:
  name: "Test model for CI"
  signals:
    - custom_CI
  data:
    - custom_CI_data
