BaseModel:
  name: "Base Model"
  backgrounds:
    - DY
    - TT
    - VV
    - EWK
    - EWK_2Mu2J_MLL_105to160_pythia
    - EWK_2Mu2J_MLL_105to160_herwig
    - W_NJets
    - ST
    - TW
    - VVV
    - TTX
    - H_mainBckg
    - TTH_inclusive
    - VH_inclusive
  signals:
    - VBFHto2Mu_m125_amcatnlo
    - VBFHto2Mu_m125_powheg
    - VBFHto2Mu_m120
    - VBFHto2Mu_m130
    - VBFHto2Mu_m125_tuneDown
    - VBFHto2Mu_m125_tuneUp
    - GluGluHto2Mu
    - GluGluHto2Mu_MiNNLO
    # - VBFHto2Mu_Herwig
  data:
    - Data_Muon

TestModel:
  name: "Test model for CI"
  backgrounds:
    - custom_CI_background
  signals:
    - custom_CI_signal
  data:
    - custom_CI_data
