BaseModel:
  name: "Base Model"
  backgrounds:
    - DY
    - DY_mll_bin
    - DY_amcatnloFXFX
    # - DYToMuMu_MiNNLO
    - DYToMuMu_amcatnloFXFX
    - TT
    - VV
    - EWK_LLJJ
    - W_NJets
    - ST
    - TW
    - VVV
    # - W
    # - EWK
    # - EWK_LLJJ_herwig
    - TTX
    - H_mainBckg
    - TTH_inclusive
    - VH_inclusive
  signals:
    - VBFHto2Mu
    - VBFHto2Mu_Herwig
    - GluGluHto2Mu
  data:
    - Data_Muon
