.DY_processors: &DY_processors
  - name: Stitcher
    module: FLAF.Processors.MCStitching
    class: MCStitcher
    config: FLAF/config/Processors/stitching_DY_amcatnlo_Vpt_NpNLO.yaml
    stages: [ AnaCache, AnaTuple ]
    dependency_level:
      AnaCache: dataset
      AnaTuple: process
