LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole:
  crossSection: LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole
  generator: pythia
  fs_nanoAOD: T2_CH_CERN:/store/group/phys_higgs/cmshmm/amarini/{}/Run3Summer2022-NANOAODSIMv12/241010_133402/
  # dirName: "0000"

LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_ext1:
  crossSection: LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole
  generator: pythia
  fs_nanoAOD: T2_CH_CERN:/store/group/phys_higgs/cmshmm/amarini/LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole/Run3Summer2022-NANOAODSIMv12/241010_133402/
  dirName: "0001"

LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_ext2:
  crossSection: LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole
  generator: pythia
  fs_nanoAOD: T2_CH_CERN:/store/group/phys_higgs/cmshmm/amarini/LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole/Run3Summer2022-NANOAODSIMv12/241010_133402/
  dirName: "0002"

LLJJ_SM_M-50_MJJ120_13p6TeV_dipole:
  crossSection: LLJJ_SM_M-50_MJJ120_13p6TeV_dipole
  generator: pythia
  fs_nanoAOD: T2_CH_CERN:/store/group/phys_higgs/cmshmm/amarini/LLJJ_SM_M-50_MJJ120_13p6TeV_dipole/Run3Summer2022-NANOAODSIMv12/241010_133237/
  dirName: "0000"

LLJJ_SM_M-50_MJJ120_13p6TeV_dipole_ext1:
  crossSection: LLJJ_SM_M-50_MJJ120_13p6TeV_dipole
  generator: pythia
  fs_nanoAOD: T2_CH_CERN:/store/group/phys_higgs/cmshmm/amarini/LLJJ_SM_M-50_MJJ120_13p6TeV_dipole/Run3Summer2022-NANOAODSIMv12/241010_133237/
  dirName: "0001"

LLJJ_SM_M-50_MJJ120_13p6TeV_herwig7:
  crossSection: LLJJ_SM_M-50_MJJ120_13p6TeV_herwig7
  generator: pythia
  fs_nanoAOD: T2_CH_CERN:/store/group/phys_higgs/cmshmm/amarini/LLJJ_SM_M-50_MJJ120_13p6TeV_herwig7/Run3Summer2022-NANOAODSIMv12/241011_074040/
  dirName: "0000"

LLJJ_SM_M-50_MJJ120_13p6TeV_herwig7_ext1:
  crossSection: LLJJ_SM_M-50_MJJ120_13p6TeV_herwig7
  generator: pythia
  fs_nanoAOD: T2_CH_CERN:/store/group/phys_higgs/cmshmm/amarini/LLJJ_SM_M-50_MJJ120_13p6TeV_herwig7/Run3Summer2022-NANOAODSIMv12/241011_074040/
  dirName: "0001"

LLJJ_SM_M-50_MJJ120_13p6TeV_herwig7_ext2:
  crossSection: LLJJ_SM_M-50_MJJ120_13p6TeV_herwig7
  generator: pythia
  fs_nanoAOD: T2_CH_CERN:/store/group/phys_higgs/cmshmm/amarini/LLJJ_SM_M-50_MJJ120_13p6TeV_herwig7/Run3Summer2022-NANOAODSIMv12/241011_074040/
  dirName: "0002"


LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter:
  crossSection: LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter
  generator: pythia
  fs_nanoAOD: T2_CH_CERN:/store/group/phys_higgs/cmshmm/amarini/LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter/Run3Summer2022-NANOAODSIMv12/250402_165919/
  dirName: "0000"


LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext1:
  crossSection: LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter
  generator: pythia
  fs_nanoAOD: T2_CH_CERN:/store/group/phys_higgs/cmshmm/amarini/LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter/Run3Summer2022-NANOAODSIMv12/250402_165919/
  dirName: "0001"

LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext2:
  crossSection: LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter
  generator: pythia
  fs_nanoAOD: T2_CH_CERN:/store/group/phys_higgs/cmshmm/amarini/LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter/Run3Summer2022-NANOAODSIMv12/250402_165919/
  dirName: "0002"

LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext3:
  crossSection: LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter
  generator: pythia
  fs_nanoAOD: T2_CH_CERN:/store/group/phys_higgs/cmshmm/amarini/LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter/Run3Summer2022-NANOAODSIMv12/250402_165919/
  dirName: "0003"

LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext4:
  crossSection: LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter
  generator: pythia
  fs_nanoAOD: T2_CH_CERN:/store/group/phys_higgs/cmshmm/amarini/LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter/Run3Summer2022-NANOAODSIMv12/250402_165919/
  dirName: "0004"

LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext5:
  crossSection: LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter
  generator: pythia
  fs_nanoAOD: T2_CH_CERN:/store/group/phys_higgs/cmshmm/amarini/LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter/Run3Summer2022-NANOAODSIMv12/250402_165919/
  dirName: "0005"

LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext6:
  crossSection: LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter
  generator: pythia
  fs_nanoAOD: T2_CH_CERN:/store/group/phys_higgs/cmshmm/amarini/LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter/Run3Summer2022-NANOAODSIMv12/250402_165919/
  dirName: "0006"

LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext7:
  crossSection: LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter
  generator: pythia
  fs_nanoAOD: T2_CH_CERN:/store/group/phys_higgs/cmshmm/amarini/LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter/Run3Summer2022-NANOAODSIMv12/250402_165919/
  dirName: "0007"

LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext8:
  crossSection: LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter
  generator: pythia
  fs_nanoAOD: T2_CH_CERN:/store/group/phys_higgs/cmshmm/amarini/LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter/Run3Summer2022-NANOAODSIMv12/250402_165919/
  dirName: "0008"

LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter_ext9:
  crossSection: LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter
  generator: pythia
  fs_nanoAOD: T2_CH_CERN:/store/group/phys_higgs/cmshmm/amarini/LLJJ_SM_M105-160_MJJ120_13p6TeV_dipole_vbffilter/Run3Summer2022-NANOAODSIMv12/250402_165919/
  dirName: "0009"

DYto2Mu_MLL_105to160_amcatnloFXFX:
  crossSection: DYto2Mu_MLL_105to160_amcatnloFXFX
  crossSectionStitch: DYto2Mu_MLL_105to160_amcatnloFXFX
  generator: amcatnlo
  miniAOD: /DYto2Mu_MLL_105to160_amcatnloFXFX/Run3Summer22MiniAODv4-130X_mcRun3_2022_realistic_v5-v1/MINIAODSIM

# missing entries to add:
# DYToMuMu-M50_13p6TeV_MiNNLO_pythia8
# DYToMuMu-M105-180_13p6TeV_MiNNLO_pythia8
# dymumu012j_5f_NLO_FXFX_M105to180 # no xs available
# dymumu012j_5f_NLO_FXFX_M105to180_vbffilter # no xs available
# DY012j_NLO_5f # no xs available

DYToMuMu-M105-180_13p6TeV_MiNNLO_pythia8:
  crossSection: DYToMuMu-M105-180_13p6TeV_MiNNLO_pythia8
  generator: pythia
  fs_nanoAOD: T2_CH_CERN:/store/group/phys_higgs/cmshmm/amarini/DYToMuMu-M105-180_13p6TeV_MiNNLO_pythia8/Run3Summer2022-NANOAODSIMv12-POWEHGFIX/241205_141647/
  dirName: "0000"

DYToMuMu-M105-180_13p6TeV_MiNNLO_pythia8_ext1:
  crossSection: DYToMuMu-M105-180_13p6TeV_MiNNLO_pythia8
  generator: pythia
  fs_nanoAOD: T2_CH_CERN:/store/group/phys_higgs/cmshmm/amarini/DYToMuMu-M105-180_13p6TeV_MiNNLO_pythia8/Run3Summer2022-NANOAODSIMv12-POWEHGFIX/241205_141647/
  dirName: "0001"

DYToMuMu-M50_13p6TeV_MiNNLO_pythia8:
  crossSection: DYto2L_M_50_amcatnloFXFX # DYToMuMu-M50_13p6TeV_MiNNLO_pythia8
  generator: pythia
  fs_nanoAOD: T2_CH_CERN:/store/group/phys_higgs/cmshmm/amarini/DYToMuMu-M50_13p6TeV_MiNNLO_pythia8/Run3Summer2022-NANOAODSIMv12-POWEHGFIX/241205_141556/
  dirName: "0000"

DYToMuMu-M50_13p6TeV_MiNNLO_pythia8_ext1:
  crossSection: DYto2L_M_50_amcatnloFXFX # DYToMuMu-M50_13p6TeV_MiNNLO_pythia8
  generator: pythia
  fs_nanoAOD: T2_CH_CERN:/store/group/phys_higgs/cmshmm/amarini/DYToMuMu-M50_13p6TeV_MiNNLO_pythia8/Run3Summer2022-NANOAODSIMv12-POWEHGFIX/241205_141556/
  dirName: "0001"

VBFHto2Mu_M-125_13p6TeV_powheg-herwig7:
  crossSection: VBFHto2Mu
  generator: pythia
  fs_nanoAOD: T2_CH_CERN:/store/group/phys_higgs/cmshmm/amarini/VBFHto2Mu_M-125_13p6TeV_powheg-herwig7/Run3Summer2022-NANOAODSIMv12/241010_115528/
  dirName: "0000"

VBFHto2Mu_M-125_13p6TeV_powheg-herwig7_ext1:
  crossSection: VBFHto2Mu
  generator: pythia
  fs_nanoAOD: T2_CH_CERN:/store/group/phys_higgs/cmshmm/amarini/VBFHto2Mu_M-125_13p6TeV_powheg-herwig7/Run3Summer2022-NANOAODSIMv12/241010_115528/
  dirName: "0001"

VBFHto2Mu_M-125_13p6TeV_powheg-herwig7_ext2:
  crossSection: VBFHto2Mu
  generator: pythia
  fs_nanoAOD: T2_CH_CERN:/store/group/phys_higgs/cmshmm/amarini/VBFHto2Mu_M-125_13p6TeV_powheg-herwig7/Run3Summer2022-NANOAODSIMv12/241010_115528/
  dirName: "0002"

GluGluHto2Mu:
  crossSection: GluGluHto2Mu
  generator: powheg

TTH_Hto2Mu:
  crossSection: TTH_Hto2Mu
  generator: powheg

VBFHto2Mu:
  crossSection: VBFHto2Mu
  generator: powheg

WminusH_Hto2Mu_WtoAll:
  crossSection: WminusH_Hto2Mu_WtoAll
  generator: powheg
WplusH_Hto2Mu_WtoAll:
  crossSection: WplusH_Hto2Mu_WtoAll
  generator: powheg
ZH_Hto2Mu_ZtoAll:
  crossSection: ZH_Hto2Mu_ZtoAll
  generator: powheg
