name: Test Setup Loading

on:
  pull_request:
    types: [ "opened", "synchronize", "reopened", "labeled" ]
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test-setup-loading:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: cms-flaf/FLAF/.github/actions/checkout-flaf@main
    
    - name: Initialize FLAF submodules
      run: |
        cd FLAF
        git submodule update --init --recursive
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml law luigi
    
    - name: Run Setup loading test
      run: |
        python tests/test_setup_loading.py
